return {
  -- disable trouble
  { "L3MON4D3/LuaSnip", enabled = false },
  { "hrsh7th/nvim-cmp", enabled = false },
  { "hrsh7th/cmp-nvim-lsp", enabled = false },
  { "hrsh7th/cmp-buffer", enabled = false },
  { "hrsh7th/cmp-path", enabled = false },
  { "saadparwaiz1/cmp_luasnip", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  { "folke/neoconf.nvim", enabled = false },
  { "folke/neodev.nvim", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "goolord/alpha-nvim", enabled = false },
  { "nvim-tree/nvim-web-devicons", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "lewis6991/gitsigns.nvim", enabled = false },
  { "lewis6991/gitsigns.nvim", enabled = false },
  { "folke/trouble.nvim", enabled = false },
}
